In [1]:
import pandas as pd

In [2]:
#datacollection
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
#preprocessing categorical data
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
#spliting input and output data
input_data=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
print(input_data)
output_data=dataset[['charges']]
print(output_data)

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]
          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
#spliting training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]
          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]
      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [7]:
#standardizing the input values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)

[[-1.5330973  -0.40713453 -0.89833872 -0.97676557 -0.50466988]
 [-0.03364163  0.32855417 -0.89833872 -0.97676557 -0.50466988]
 [ 0.89459283  2.56690911  3.25603402 -0.97676557 -0.50466988]
 ...
 [ 0.03776102 -0.91016269 -0.89833872  1.02378711 -0.50466988]
 [-1.46169465  0.76659782 -0.89833872  1.02378711 -0.50466988]
 [-0.46205754 -1.96596021 -0.06746417 -0.97676557 -0.50466988]]
[[ 0.89459283 -0.08863026 -0.06746417  1.02378711 -0.50466988]
 [ 0.53757957 -0.22180837 -0.06746417 -0.97676557 -0.50466988]
 [ 0.60898222  1.57449152  0.76341038  1.02378711  1.98149332]
 ...
 [ 1.10880078  1.20785059 -0.89833872  1.02378711 -0.50466988]
 [ 1.75142463  1.34905148 -0.06746417  1.02378711 -0.50466988]
 [ 1.60861933 -0.92299913 -0.89833872 -0.97676557 -0.50466988]]

In [9]:
#Ada boosting algorithm
from sklearn.ensemble import AdaBoostRegressor

regressor=AdaBoostRegressor(n_estimators=50,learning_rate=1.0,loss='linear')
regressor=regressor.fit(x_train,y_train)

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
y_predict=regressor.predict(x_test)
print(y_predict)
print(y_test)

[16597.46336897 13352.9870372  46166.68817564 15793.90645792
 12741.9741471   7411.97198748  7411.97198748 16597.46336897
  9581.01528614  9581.01528614  9581.01528614 16597.46336897
 11724.33845969  7411.97198748 20196.48811057 16597.46336897
 15793.90645792  7411.97198748  9581.01528614 37249.69929102
 26100.49904378 18339.88801198 12741.9741471  26100.49904378
  7411.97198748  7411.97198748  7411.97198748 11129.07909415
  7411.97198748 11724.33845969 11129.07909415 46166.68817564
 15793.90645792 12741.9741471  20196.48811057  7411.97198748
 11724.33845969 37249.69929102 43470.14738954  7411.97198748
  7411.97198748  7411.97198748 20196.48811057 46166.68817564
 37249.69929102  9581.01528614 16597.46336897  7411.97198748
  7411.97198748 16597.46336897  7411.97198748  9581.01528614
 26100.49904378 46166.68817564 12741.9741471   7411.97198748
  7411.97198748 12741.9741471  11724.33845969 18339.88801198
  7411.97198748 46166.68817564 18339.88801198 16597.46336897
 13352.9870372  15994.85780476 37249.69929102 43470.14738954
  9581.01528614 11129.07909415 15793.90645792 16597.46336897
 20196.48811057 15793.90645792 15793.90645792 15793.90645792
 11724.33845969 11724.33845969 20196.48811057 46166.68817564
 12741.9741471  43470.14738954  7411.97198748 11724.33845969
 43470.14738954 20196.48811057  7411.97198748  7411.97198748
 18339.88801198 37249.69929102  9581.01528614 12741.9741471
  7411.97198748 11724.33845969  7411.97198748  7411.97198748
 46166.68817564 46166.68817564  9581.01528614 12741.9741471
  7411.97198748  7411.97198748  9581.01528614 43470.14738954
 26100.49904378  7411.97198748 12741.9741471   7411.97198748
 12741.9741471  46166.68817564 18339.88801198  9581.01528614
 13352.9870372  37249.69929102 46166.68817564 11129.07909415
  7411.97198748 12741.9741471  18339.88801198 11724.33845969
 43470.14738954 12741.9741471  15793.90645792  9581.01528614
 11724.33845969  9581.01528614 26100.49904378 26100.49904378
 46166.68817564  7411.97198748 11724.33845969  7411.97198748
  7411.97198748 12741.9741471  27258.49127775 43470.14738954
 26100.49904378 16597.46336897 26100.49904378  7411.97198748
  7411.97198748 12741.9741471  13352.9870372  12741.9741471
  7411.97198748 15793.90645792 18339.88801198  9581.01528614
  7411.97198748 16597.46336897  7411.97198748 37249.69929102
 16515.81751465  7411.97198748  7411.97198748  7411.97198748
  7411.97198748  7411.97198748 16597.46336897 13352.9870372
  9581.01528614 15793.90645792 15793.90645792 15994.85780476
  7411.97198748  9581.01528614 20196.48811057  9581.01528614
  7411.97198748  7411.97198748  9581.01528614  9581.01528614
 11724.33845969  7411.97198748  9581.01528614  9581.01528614
  9581.01528614  7411.97198748 26100.49904378  7411.97198748
 18339.88801198  9581.01528614 12741.9741471   7411.97198748
  9581.01528614 26100.49904378  7411.97198748  7411.97198748
 15793.90645792 13352.9870372  46166.68817564  9581.01528614
  7411.97198748 26100.49904378  7411.97198748  7411.97198748
  9581.01528614  9581.01528614  9581.01528614  7411.97198748
 16597.46336897 46166.68817564 18339.88801198 20196.48811057
  9581.01528614 46166.68817564  9581.01528614 12741.9741471
  9581.01528614  7411.97198748 13352.9870372  15793.90645792
  9581.01528614  7411.97198748  7411.97198748  7411.97198748
  9581.01528614  7411.97198748 18339.88801198  9581.01528614
  9581.01528614 10362.42312437 12741.9741471   7411.97198748
 12741.9741471  15793.90645792 18339.88801198 12741.9741471
  9581.01528614  7411.97198748  7411.97198748 11724.33845969
 15793.90645792  9581.01528614  7411.97198748 11129.07909415
 13352.9870372  37249.69929102  7411.97198748 18339.88801198
  7411.97198748 37249.69929102 11129.07909415 11724.33845969
 11724.33845969 16597.46336897  9581.01528614 11724.33845969
  7411.97198748  7411.97198748 20196.48811057 46166.68817564
  9581.01528614  7411.97198748  7411.97198748  7411.97198748
 11724.33845969  7411.97198748  9581.01528614  7411.97198748
 11724.33845969 26100.49904378 46166.68817564 18339.88801198
  7411.97198748 12741.9741471  37249.69929102 11724.33845969
 43470.14738954  7411.97198748 37249.69929102  9581.01528614
 16597.46336897  9581.01528614 43470.14738954  7411.97198748
 12741.9741471  11724.33845969  7411.97198748 18339.88801198
 12741.9741471   7411.97198748 15793.90645792  7411.97198748
  7411.97198748  9581.01528614 11129.07909415 26100.49904378
  7411.97198748  7411.97198748  9581.01528614 46166.68817564
 13352.9870372   7411.97198748 18339.88801198 16597.46336897
 37249.69929102  7411.97198748  7411.97198748 12741.9741471
  7411.97198748  9581.01528614 20196.48811057 20196.48811057
 15793.90645792  7411.97198748  7411.97198748 11724.33845969
 12741.9741471  20196.48811057 20196.48811057  9581.01528614
 20196.48811057  7411.97198748  7411.97198748  7411.97198748
 12741.9741471   9581.01528614 11724.33845969 46166.68817564
  9581.01528614  7411.97198748  7411.97198748 12741.9741471
  7411.97198748 12741.9741471  46166.68817564 20196.48811057
 13352.9870372  43470.14738954 18339.88801198  9581.01528614
 16515.81751465  9581.01528614 26100.49904378  7411.97198748
 15793.90645792  7411.97198748 20196.48811057  7411.97198748
 26100.49904378  7411.97198748  7411.97198748 37249.69929102
  9581.01528614  7411.97198748 26100.49904378  7411.97198748
 11724.33845969  9581.01528614 13352.9870372   7411.97198748
  9581.01528614  9581.01528614 46166.68817564 12741.9741471
 37249.69929102 37249.69929102  7411.97198748 11129.07909415
  7411.97198748  7411.97198748  9581.01528614 13352.9870372
 46166.68817564 12741.9741471   7411.97198748 15793.90645792
  7411.97198748 11724.33845969  7411.97198748  7411.97198748
  7411.97198748 37249.69929102  9581.01528614  7411.97198748
 43470.14738954 16597.46336897 46166.68817564 12741.9741471
  7411.97198748  7411.97198748  7411.97198748 16597.46336897
  7411.97198748  7411.97198748 16597.46336897  9581.01528614
  7411.97198748  9581.01528614  7411.97198748 37249.69929102
  7411.97198748 12741.9741471   7411.97198748  7411.97198748
 12741.9741471   7411.97198748 20196.48811057 12741.9741471
 18339.88801198 15793.90645792]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [11]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.8476807351567384