In [2]:
pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.7.0-py3-none-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: narwhals>=1.15 in c:\anaconda3\lib\site-packages (from lightgbm) (2.7.0)
Requirement already satisfied: numpy>=1.21.3 in c:\anaconda3\lib\site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from lightgbm) (1.16.3)
Downloading lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 11.1 MB/s  0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.7.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import lightgbm as lgb

In [2]:
#datacollection
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
#preprocessing categorical data
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
#spliting input and output data
input_data=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
print(input_data)
output_data=dataset[['charges']]
print(output_data)

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]
          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
#spliting training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]
          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]
      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [7]:
#standardizing the input values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)

[[-1.5330973  -0.40713453 -0.89833872 -0.97676557 -0.50466988]
 [-0.03364163  0.32855417 -0.89833872 -0.97676557 -0.50466988]
 [ 0.89459283  2.56690911  3.25603402 -0.97676557 -0.50466988]
 ...
 [ 0.03776102 -0.91016269 -0.89833872  1.02378711 -0.50466988]
 [-1.46169465  0.76659782 -0.89833872  1.02378711 -0.50466988]
 [-0.46205754 -1.96596021 -0.06746417 -0.97676557 -0.50466988]]
[[ 0.89459283 -0.08863026 -0.06746417  1.02378711 -0.50466988]
 [ 0.53757957 -0.22180837 -0.06746417 -0.97676557 -0.50466988]
 [ 0.60898222  1.57449152  0.76341038  1.02378711  1.98149332]
 ...
 [ 1.10880078  1.20785059 -0.89833872  1.02378711 -0.50466988]
 [ 1.75142463  1.34905148 -0.06746417  1.02378711 -0.50466988]
 [ 1.60861933 -0.92299913 -0.89833872 -0.97676557 -0.50466988]]

In [9]:
#LG boosting algorithm
from lightgbm import LGBMRegressor
regressor=LGBMRegressor(boosting_type='gbdt',num_leaves=31,max_depth=-1,learning_rate=0.1,n_estimators=100)
regressor=regressor.fit(x_train,y_train)

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000276 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 316
[LightGBM] [Info] Number of data points in the train set: 936, number of used features: 5
[LightGBM] [Info] Start training from score 13232.916456

In [10]:
y_predict=regressor.predict(x_test)
print(y_predict)
print(y_test)

[ 9991.6955793   8091.82232526 44242.48227634 12687.44522847
  9549.72199712  7018.83625386  2059.80986271 12836.38664824
  8154.60812735  5600.27468473  6995.75270097 16394.98768397
  8666.54783402  8467.84203633 21901.89116803 11282.34366058
 15600.731768    3049.48888456  5836.75691035 34326.88991511
 23764.69634507 17261.24792414 10063.61649756 26611.45880664
  4715.75225508  6176.54289302  5196.03595184  6820.32924539
  2412.06245212 11710.19835489  7319.78739296 49117.04832809
 17615.94190787 11732.22331163 17402.43556847  4461.7974098
 11660.99643497 37955.66338055 38472.29958032  3324.83909292
  6210.34268468  5844.37791358 19881.6746591  48842.85883941
 36669.5849967   3136.07901425 11784.5460969   8232.94767833
  5140.0193479  12138.94472456  1326.74223092  3068.28266267
 25245.61958372 46553.80261775 12667.31848606  8360.09980477
  4183.73558571 11380.41209627  8328.83045719 19089.35691893
  2113.8433097  45759.50229063 17170.82779452 16258.05591735
 12794.58199634  7953.62976717 33721.96655422 38201.37867273
  4193.33923403  9394.5095938  16255.45796862 10437.50558881
 16307.08234839 16416.22169428 16006.23923564 16448.30865472
  9380.83713045 11818.89857822 18284.01119311 48477.9089746
  9674.09252801 49316.53158333  3210.44911128 10655.55682872
 40731.60053923 19101.20652733  3680.79796812  2771.69822042
 16188.77988867 38137.36528686  3902.3501434  14038.78251602
  4097.51633783 11924.5827493   7762.36090497  3251.83820133
 46050.02407774 43348.8881428   4234.70890756 10717.70695184
  2841.54236533 11103.53866936  7634.21136684 39555.36618112
 28472.8893836   4451.4797245   9808.00571582  3545.8814306
 12411.11874164 46125.13905028 11522.33401895  4246.28195832
  7565.88809224 34149.70437346 49984.4316481   7771.12155707
  1972.0915799  11252.98317284 21743.69764593  8685.92602018
 42979.7926694  11252.08921244 13411.02728108  8467.11982076
 14567.86312718  6767.75270098 26251.56734812 26963.93920926
 48984.93787043  1631.01849336 14985.38210113  4916.35498304
  6812.99167557  9152.46249251 28892.81850781 38151.88681943
 23014.74241927 12741.34217965 23244.73091648  8479.63536825
  2867.17935298 13765.21921651 14410.49402663 12023.62588351
  5608.29856784 14035.54848476 20502.97807597 10053.7147855
  1427.84064105 11431.94448151  7411.47265531 40335.88227111
  9448.92755763  5268.81966636  4045.08976755  8110.9168767
  3915.66958032  3162.61024033 11282.34366058 10929.68693829
  6329.43249746 13844.14624686 13439.39270883  7592.81806479
  5798.83195809  7633.85673233 16031.26943791  8161.52406578
  6432.12283512  2141.69976862 11884.99759568  8820.12895759
 11436.56438468  1813.25703518 10097.6029159   7732.94164442
  5496.61955998  6860.37756012 26499.19196884  1755.03207462
 15822.09483995  6322.29741613 11323.94840322  7395.7924564
  6952.79260295 26993.97779619  3442.14718381  4247.44745403
 13139.86666884 13345.24686556 42556.3045663   6799.86914017
  4842.06074261 23039.37772803  1392.31143498  3732.09799338
  9443.22555591  8143.17281413  6966.78995927  4789.26396428
 13980.05004383 45995.34775728 18038.21786115 18542.09456556
  8692.71215716 42341.96699458  3312.93736112  9886.69109575
  8179.25975022  2100.29216872  8852.64089636 14000.76745716
  8783.63389881  2889.28288263  6926.66531242  5405.71835387
  7660.00665294  7310.7454725  14346.44034829  6824.60071901
 10998.79890335  7434.82353625  9096.42900379  5555.94297729
 13132.15227934 14296.53451142 21822.2214739  14131.32957494
  5874.58702734  1023.13267669  6148.33447501  6977.5581541
 15118.50854159  5663.2272885   6136.64753286  7534.22925731
 15007.33779177 36655.6876841   6274.69881393 11848.67406806
  8449.80912283 37917.45126114  8109.64938607  7721.52953695
 11018.80811973  9302.1848303   3151.19158163  8206.93291844
  4805.15824041  6919.63047146 20391.21204186 45543.01934299
  3937.45278323  3991.20192358  2479.03955461  2998.17264965
  9062.59934796  1197.03319121  4961.70893113  9354.32165768
  8726.17130118 26058.33874594 45566.26423414 17498.05709856
  8335.40647048 10739.32494676 45694.41475828 10090.08809215
 39749.99505802  2919.83425746 38425.76021935  6589.5324402
 12540.99608725  8447.83156926 38695.19409036  5424.53490023
 10377.90336506 10225.5319175   4123.3815017  17367.59151367
 12726.05614016  8139.14194998 15232.89136431  7393.58538186
  7315.79761074  3942.25077663  9307.34375198 21356.22249466
  3468.56063858   601.71307502  2101.68600377 49167.45956784
 10846.61456672  2863.56493081 16981.66456651 14372.07377873
 34463.2206038   9287.85685479  5915.53062606  8351.04428986
  4015.59657091  4051.38903958 16833.34305063 16779.04802135
 15210.0430137   2074.58000733  1845.59609163 14745.89798579
 10775.48794803 16085.52964126 22004.10210355  8820.16507173
 16764.67439745  4620.18179599  9166.85803342  8353.22978105
 15561.64791047  2557.12995276  7482.57196903 47048.84741284
  3891.32685427  5669.21619722  2383.23109734 11088.31250266
  6391.39928045 11469.10233774 46708.40046003 18426.18156418
  7954.74192912 47005.59544413 19004.29705816  8039.46496633
  9217.41092835  3235.32743595 27987.52113673  3848.01339423
 14666.99140393  2433.55568335 16943.37619423  4531.83745139
 25155.97354788  9548.71830072  5229.70758069 42094.45452709
  5966.69365255  5344.98646832 27437.42073698  4680.01979636
 10479.25277339  3984.85680894 12860.67260088  3665.15070054
  7234.57600145  5247.43955775 45024.30082981 12373.70562172
 37305.15948845 39303.1728221   6477.31274885 12645.5763436
  2615.27555378  6283.90773849  5469.16250588  9318.05508854
 46905.65324553 10068.97924221  1862.17291655 15250.54795286
  2682.7959322  12318.03291773  7069.6015567   1887.54119716
  3322.53278545 35925.36094361  5627.17757375  1982.84447026
 42603.07722099 12667.39945953 42982.8367673   9674.30912227
 10817.3427092   4072.80770678  1457.41001144 13590.30929692
  7291.03952768  3408.71475031  9898.13863492  7327.33751635
  6986.16351162  6565.03260907  7820.2977128  43152.75311674
  3836.36417955 12098.50733111  5752.32090156 13074.29206607
 10251.84095203  7413.22170701 16598.45242354 12639.062082
 15977.50718108 18732.9191425 ]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [11]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.8699321391117371