In [1]:
import pandas as pd

In [ ]:
pip install --upgrade xgboost

In [2]:
#datacollection
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
#preprocessing categorical data
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
#spliting input and output data
input_data=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
print(input_data)
output_data=dataset[['charges']]
print(output_data)

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]
          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
#spliting training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]
          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]
      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [7]:
#standardizing the input values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)

[[-1.5330973  -0.40713453 -0.89833872 -0.97676557 -0.50466988]
 [-0.03364163  0.32855417 -0.89833872 -0.97676557 -0.50466988]
 [ 0.89459283  2.56690911  3.25603402 -0.97676557 -0.50466988]
 ...
 [ 0.03776102 -0.91016269 -0.89833872  1.02378711 -0.50466988]
 [-1.46169465  0.76659782 -0.89833872  1.02378711 -0.50466988]
 [-0.46205754 -1.96596021 -0.06746417 -0.97676557 -0.50466988]]
[[ 0.89459283 -0.08863026 -0.06746417  1.02378711 -0.50466988]
 [ 0.53757957 -0.22180837 -0.06746417 -0.97676557 -0.50466988]
 [ 0.60898222  1.57449152  0.76341038  1.02378711  1.98149332]
 ...
 [ 1.10880078  1.20785059 -0.89833872  1.02378711 -0.50466988]
 [ 1.75142463  1.34905148 -0.06746417  1.02378711 -0.50466988]
 [ 1.60861933 -0.92299913 -0.89833872 -0.97676557 -0.50466988]]

In [8]:
#XG boosting algorithm
import xgboost as xgb

regressor=xgb.XGBRegressor(objective='reg:squarederror',
                         n_estimators=100, random_state=42)

regressor=regressor.fit(x_train,y_train)

In [9]:
y_predict=regressor.predict(x_test)
print(y_predict)
print(y_test)

[10005.267    9240.748   45179.78    11771.357    9868.739    5211.0815
  1720.6288   9709.564    7822.1333   4970.6357   6734.1562  21753.877
  9792.268    3878.9312  25894.209   13247.515   13231.901    2705.2004
  5951.629   33508.945   24032.36    16804.28     9840.145   33113.1
 14045.153    4050.4404   6761.03     6810.7944   3352.9253   8146.14
  7805.293   48055.855   17336.62    13225.092   20410.297    4948.806
  7672.0117  35048.133   39099.926    1606.6152   6572.992    4886.1807
 18760.895   47553.96    38485.355    3006.1477  15184.939    9208.623
  4219.242   12845.847    2249.6785   2453.8643  27479.38    48229.91
 11658.968    4180.028    1992.3093  11747.091    9445.151   17729.137
  1877.2103  44428.945   16625.803   23073.48    16785.074    8982.533
 33170.5     38818.426    3452.7664  12329.401   16473.98    10634.558
 15288.863   14703.26    12729.457   13508.017    8706.604   10087.556
 17720.693   51381.332   11443.81    53274.062    2811.7388  10394.791
 39403.457   18435.467    8458.055    3516.0293  10576.179   39333.715
  5577.872   16301.1875   6371.0635  11945.461    5866.2324   4302.382
 42541.117   52961.89     6851.1055  10743.558    2077.4802   6265.1987
  6365.8076  40681.71    26634.145    4849.7163  11436.43     4031.5537
 13099.037   45258.668   12696.243    4092.377    9075.881   34226.93
 49883.797   11106.149    3392.0168  10741.7     23140.871    8592.901
 41669.81    11673.013   14797.215   13226.777    9646.039    5789.8486
 31767.037   26573.375   47607.457    1694.4244  11061.348   10702.734
  7735.742    8648.559   47236.184   37504.805   21423.965   19614.111
 22946.12     6353.6987   1056.8613  12110.133   18572.064   11077.14
  4417.5635  14960.706   26460.598    9506.722    2127.834   13562.644
  4722.4844  38722.324   11832.5205  10594.707    3156.034    6854.015
  3381.8972   3300.9856  13247.515    8898.214    5253.554   13190.211
 13248.347    8549.299    5519.727   11727.701   15084.856    5102.9014
  6796.9927   1965.971    5210.341   10019.575   12673.83      474.60812
 11631.529   11723.745    5028.799    7090.017   25422.229    1594.0913
 17429.533    5452.0356  11040.981    5092.2656   6892.8965  26262.137
  3979.409    4683.7773  15472.993   18469.213   40859.707    4289.468
  5101.9053  25197.195     270.43304  4174.713    6676.9907   9338.687
  6217.82     5195.461   11655.956   44834.324   16217.929   18645.607
  7002.302   41768.832    3733.9465  10309.409    6907.724    1237.7185
  8830.466   13803.485    9595.158    1578.7334   6549.104    4900.2983
  6649.9707  12023.257   15482.041    8575.192   13518.204   18250.125
 11042.69     4845.2065  12394.654   13895.497   22885.322   12524.467
  5793.0796   1784.9977  19372.543    7412.1304  17467.084    4570.0825
  4317.904    7359.99    18817.164   34854.28     6157.9604  10943.195
 13917.12    35326.53     6971.4727  10317.391   10856.542   10865.576
  4017.009    8498.141    1957.837    6018.7188  19378.543   42921.652
  4863.9956   8458.055    3616.53     1588.8677   9890.297    1833.8644
  6548.9844  22597.58     7807.9985  27241.695   44310.926   15383.564
  6682.0454  10768.393   42369.297    8137.4214  41399.98     1813.4763
 37727.152    5509.5356  11528.386    7624.042   39015.133    5213.3403
 11315.378    8138.0073   2337.8787  18830.309   11605.99     5462.3867
 19443.143   19475.582    5465.266    4040.942    5781.918   20221.113
  3003.1406   1488.1604   2435.07    51233.35    11547.902    5898.9766
 17709.441   11084.205   34690.836   11674.871    3872.7407   8722.479
  2285.5916   3710.957   26206.877   18132.074   12656.901    2704.339
  2226.9165  14507.089    9427.692   14035.857   20538.021    9848.961
 18114.252     741.12506  6907.782    5922.4863  17618.03     2959.8406
 12382.297   46178.863    3595.4153   5025.629    2427.7095   9858.595
  4722.381   14081.004   46081.355   17009.654    8857.849   46183.695
 18142.605    6156.2383  10249.45     5690.9463  28388.666    3992.8716
 16241.905    1538.0917  19826.164    2775.5305  23638.814   17606.027
  4811.407   41605.36     5841.4844   4893.249   28892.281    2655.5093
  9379.791    2923.3425  18087.771    3742.966    6480.447    5195.3623
 45997.145    9435.667   50387.85    38184.38     6066.2427  17684.367
  1946.4602   3923.7932   5177.378    7948.3027  48888.03    10539.833
  3180.7048  19439.295    1042.6693  12396.643    5783.168    3361.085
  3477.9827  36965.867    7764.7935    834.5324  42227.25    10388.308
 47814.242   10888.471    5418.0767   3816.1277   1717.4915  19338.928
  9772.599    1553.445   10254.589    7161.323    6386.152    4065.238
  6094.019   42978.125    5233.828   10752.687    5735.024   21540.676
 10743.558    4165.426   18699.135   11229.403   19923.418   17228.145  ]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [10]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.8157111406326294