In [1]:
import pandas as pd

In [2]:
#1.datacollection--importing data as a csv format
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#2.Data pre-processing as state column is odinal type of data--it will preprocess as one hot code
#drop_first will remove dummy_column if it set to True by default false
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
#to see all the column names
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
#spliting input and output data
input_data=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
print(input_data)
output_data=dataset[['charges']]
print(output_data)

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]
          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
#splitting train and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]
          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]
      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
#Module creation using multiple linear
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor=regressor.fit(x_train,y_train)

#indentifying slope of 5 inputs
weight=regressor.coef_
print(weight)

#indetifyint bias 
bias=regressor.intercept_
print(bias)

[[3610.51960788 2000.92823398  565.16490411  -20.86836183 9419.60171825]]
[13232.91646718]

In [11]:
#Identifying the prediction score
y_predict=regressor.predict(x_test)
print("Predicted_output -",y_predict,"  Actual_output -",y_test)

Predicted_output - [[11472.23618644]
 [ 9958.50125569]
 [37657.06917237]
 [15949.13223617]
 [ 6885.72312017]
 [ 3528.88810655]
 [ 1031.86224676]
 [14181.1024054 ]
 [ 8847.14792524]
 [ 7275.30131109]
 [ 4216.86216451]
 [10190.14526672]
 [ 9097.46039634]
 [ 4255.14691858]
 [27430.50340855]
 [11282.58288365]
 [11177.22736522]
 [ 5504.64625133]
 [ 8030.81149341]
 [26327.41490839]
 [33367.35431038]
 [14177.00561427]
 [11261.11883838]
 [32413.15484705]
 [ 4414.81928993]
 [ 8606.98618122]
 [  712.30206629]
 [10258.50678538]
 [ 4198.66143865]
 [10231.92533963]
 [ 8874.73800132]
 [40207.90493832]
 [15892.29406482]
 [14055.58336707]
 [24136.79051345]
 [ 4643.98226168]
 [12953.8618379 ]
 [30694.2595505 ]
 [33135.3543329 ]
 [ 3790.06798605]
 [ 3598.22643981]
 [ 4347.64393443]
 [29853.09596525]
 [39076.04912317]
 [27832.89698787]
 [ 4787.97369821]
 [11176.63306955]
 [ 7646.91121556]
 [ 3192.01904016]
 [10805.99433047]
 [ 5065.92896438]
 [ 3216.91828843]
 [33153.3686017 ]
 [37813.274525  ]
 [16350.82043262]
 [ 6496.18828402]
 [ 5975.77104239]
 [ 9270.23614952]
 [ 9527.79368838]
 [11646.80849929]
 [ 2013.64286192]
 [38624.78787957]
 [15408.08854282]
 [12100.4420692 ]
 [13591.52763834]
 [14242.04217029]
 [25929.95311932]
 [31761.49314429]
 [ 1323.73583741]
 [10004.08707152]
 [12722.4892586 ]
 [12035.6438424 ]
 [25240.62666383]
 [16015.25996901]
 [11127.47351024]
 [12255.99956035]
 [ 6919.47669201]
 [10036.73137746]
 [29574.317679  ]
 [39169.57567261]
 [11621.3060311 ]
 [37279.82514958]
 [ 3881.85961904]
 [ 9667.63149296]
 [34098.94314645]
 [29146.87823351]
 [ 8728.09953173]
 [ 4577.5545564 ]
 [12409.9787646 ]
 [30387.11371045]
 [ 9526.89529843]
 [11679.73905104]
 [ 7655.57818125]
 [ 9418.048583  ]
 [ 7798.98667454]
 [ 6788.19149092]
 [35350.43837577]
 [33298.07914773]
 [ 7396.48110723]
 [15276.56416569]
 [ 4284.13730876]
 [ 8509.66281309]
 [ 6695.31760535]
 [31654.59549627]
 [32645.2554601 ]
 [ 1796.53237431]
 [ 9433.27138843]
 [ 6324.4316128 ]
 [14047.20417457]
 [37318.48371857]
 [10165.89387993]
 [10771.46436833]
 [10058.98250526]
 [26147.32131203]
 [40010.1530396 ]
 [ 8055.49094151]
 [  589.92238036]
 [ 9331.23755763]
 [15492.15517459]
 [ 9434.27194134]
 [35362.37605772]
 [ 7235.02590284]
 [17188.08176122]
 [ 9061.04781242]
 [ 8584.71696434]
 [ 2854.7868307 ]
 [32335.32860831]
 [31210.53620626]
 [39598.01002179]
 [ 5149.0941514 ]
 [ 9795.94679706]
 [ 3853.19774202]
 [ 8062.09447759]
 [ 8247.00724961]
 [31779.10353006]
 [29973.54620025]
 [30058.22170115]
 [ 9329.70435227]
 [32840.2927927 ]
 [ 3084.20622075]
 [ 3347.00512712]
 [10955.74865474]
 [13515.3642212 ]
 [12344.98600333]
 [ 5248.99810696]
 [15990.52780192]
 [15347.688607  ]
 [ 2253.50463349]
 [ -216.11913467]
 [10466.012925  ]
 [ 6962.46383133]
 [31806.55179064]
 [11888.66160562]
 [ 2652.4331823 ]
 [ 6029.34261932]
 [ 8295.16298101]
 [ 4107.43512066]
 [ 2440.53355411]
 [11269.74048194]
 [12356.88141793]
 [ 6732.10989402]
 [16704.57597286]
 [11706.98688732]
 [14264.50592165]
 [ 2780.52868622]
 [ 6763.79676123]
 [23226.63801136]
 [ 7134.04534393]
 [ 4994.10806444]
 [ 5367.7781235 ]
 [ 6445.53298429]
 [ 4720.78789108]
 [ 9819.07366393]
 [ 5601.43612018]
 [ 5998.48769644]
 [ 7031.22923301]
 [ 3287.25480039]
 [ 5439.97611338]
 [37515.87812345]
 [  929.11258146]
 [12474.78744303]
 [ 8761.10392596]
 [13514.89716756]
 [ 5668.50603772]
 [ 4803.55811932]
 [35874.01349884]
 [ 3759.85680281]
 [ 2302.13549594]
 [15025.74237359]
 [12219.89740051]
 [34427.44347197]
 [ 5190.85133282]
 [ 6008.61553204]
 [31534.39251474]
 [ 5783.78768064]
 [ 2371.57209056]
 [ 7956.01504726]
 [ 9510.18963241]
 [ 8288.71760188]
 [ 5543.12073747]
 [12703.81187429]
 [38696.43124668]
 [13583.69719915]
 [29035.69338171]
 [ 6503.62376443]
 [35708.06435694]
 [ 3306.87109439]
 [12254.78921892]
 [ 9418.15402097]
 [ 6350.21140256]
 [11115.25959413]
 [14113.63187985]
 [ 5018.61235393]
 [ 4595.57600181]
 [ 8186.94475119]
 [ 1601.02798806]
 [ 7435.77861346]
 [ 4026.42245976]
 [13496.83910402]
 [ 3971.6703689 ]
 [10317.00297593]
 [ 6878.39719956]
 [ 9595.82257204]
 [ 1921.44581852]
 [13522.28145638]
 [16570.03072738]
 [15361.71717186]
 [10985.907119  ]
 [ 5886.96387985]
 [ 2610.10915849]
 [ 2218.16865292]
 [12887.21105742]
 [14454.30821656]
 [ 4526.72409806]
 [ 4255.02775396]
 [ 9748.13003046]
 [ 9570.97124035]
 [27480.62040661]
 [ 7164.7212066 ]
 [10170.52897273]
 [ 6600.43781156]
 [29322.19492157]
 [11363.0724969 ]
 [ 7080.36985642]
 [10063.90231648]
 [12038.25449793]
 [ 2519.67404486]
 [10600.0213962 ]
 [ 1056.54169486]
 [ 6626.59294363]
 [28676.70760617]
 [38880.16022976]
 [ 6564.98831561]
 [ 8383.6126497 ]
 [ 1946.88336847]
 [  -77.41065243]
 [10791.34164243]
 [ 4414.22979667]
 [ 4795.04603556]
 [ 2824.75798269]
 [ 7444.35234044]
 [33582.29418279]
 [37582.05292604]
 [14656.28499525]
 [ 8060.12603432]
 [15527.94363533]
 [33041.58052999]
 [ 9129.26490077]
 [33684.77088895]
 [ 3595.51623614]
 [30003.2718008 ]
 [ 8391.10412411]
 [13765.51526034]
 [ 3928.13272866]
 [32371.39286322]
 [ 7852.80550494]
 [11629.67477197]
 [ 9654.9123777 ]
 [ 3927.34152429]
 [13094.79974353]
 [11618.39540313]
 [ 8164.99512323]
 [12885.26679242]
 [ 2251.89040904]
 [10062.28809202]
 [ 5737.82911695]
 [11363.6676394 ]
 [31029.61958981]
 [10012.32925092]
 [  715.60765306]
 [  357.03468478]
 [39238.61403342]
 [ 9299.01238875]
 [ 6896.39926911]
 [13827.7028316 ]
 [12992.11324885]
 [27372.1231076 ]
 [ 7521.40827808]
 [ 7185.94280081]
 [12413.41396761]
 [ 2620.44634264]
 [ 3990.78170434]
 [24524.02948058]
 [26268.27650559]
 [13532.51320255]
 [ 2764.21797899]
 [ 5205.11822691]
 [ 9739.93164579]
 [11981.88818262]
 [22955.99493916]
 [30475.82848109]
 [10348.15634387]
 [23715.60191261]
 [ 2631.69389576]
 [11598.02689711]
 [ 7649.69375468]
 [ 7867.56690595]
 [  473.26896404]
 [ 7343.62863981]
 [35209.94051046]
 [ 5655.78844985]
 [ 5773.69447495]
 [   69.63475497]
 [11018.11856123]
 [ 6826.23791576]
 [10205.73121522]
 [39182.07583452]
 [27374.02685287]
 [11068.05322406]
 [35563.81041291]
 [14587.30980505]
 [ 6625.62658066]
 [11159.85530868]
 [ 7150.49330485]
 [36420.47868696]
 [ 6162.12440764]
 [10744.75939553]
 [ 1166.8778209 ]
 [24357.72199802]
 [ 1782.73733627]
 [34708.26076897]
 [11417.29108849]
 [ 1682.89829895]
 [31485.73572639]
 [ 7006.27399073]
 [ 5635.35241078]
 [38102.12312547]
 [ 2559.44493452]
 [ 9179.38189882]
 [ 2492.08396878]
 [13164.70904101]
 [ 1472.14256657]
 [11131.65156106]
 [ 7179.63596216]
 [35932.86238083]
 [ 7637.35631154]
 [30295.45016631]
 [29539.14877962]
 [ 7243.38091706]
 [10334.95972334]
 [ 1735.92592498]
 [ 2640.92028663]
 [ 3601.35686796]
 [12518.29198076]
 [37163.53662395]
 [10204.76812726]
 [  771.15094828]
 [11041.42951096]
 [ 4824.8339599 ]
 [10170.87273992]
 [ 5149.5222127 ]
 [ 7286.04870806]
 [ 4432.30570869]
 [28082.66070566]
 [ 4035.21926193]
 [ -741.9944892 ]
 [33229.57581358]
 [13038.65650341]
 [36129.12334154]
 [10334.14478067]
 [ 7478.4601311 ]
 [ -160.93898251]
 [ 2401.48330135]
 [11917.44829648]
 [ 6094.33865561]
 [ 2831.40378612]
 [11700.19926839]
 [ 8137.60523085]
 [ 7365.15020647]
 [ 5009.45240869]
 [ 2900.37897632]
 [32128.92608535]
 [ 3349.55261203]
 [ 9051.92577211]
 [ 4838.02905304]
 [12507.77071376]
 [15051.82213579]
 [ 7500.3343892 ]
 [26863.05580228]
 [14370.22220892]
 [17442.54221504]
 [11952.89779244]]   Actual_output -           charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [12]:
#identifying the evaluation metrics R2 value
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.789479034986701