In [1]:
import pandas as pd

In [2]:
#datacollection
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
#preprocessing categorical data
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
#spliting input and output data
input_data=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
print(input_data)
output_data=dataset[['charges']]
print(output_data)

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]
          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
#spliting training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]
          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]
      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [7]:
#standardizing the input values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)

[[-1.5330973  -0.40713453 -0.89833872 -0.97676557 -0.50466988]
 [-0.03364163  0.32855417 -0.89833872 -0.97676557 -0.50466988]
 [ 0.89459283  2.56690911  3.25603402 -0.97676557 -0.50466988]
 ...
 [ 0.03776102 -0.91016269 -0.89833872  1.02378711 -0.50466988]
 [-1.46169465  0.76659782 -0.89833872  1.02378711 -0.50466988]
 [-0.46205754 -1.96596021 -0.06746417 -0.97676557 -0.50466988]]
[[ 0.89459283 -0.08863026 -0.06746417  1.02378711 -0.50466988]
 [ 0.53757957 -0.22180837 -0.06746417 -0.97676557 -0.50466988]
 [ 0.60898222  1.57449152  0.76341038  1.02378711  1.98149332]
 ...
 [ 1.10880078  1.20785059 -0.89833872  1.02378711 -0.50466988]
 [ 1.75142463  1.34905148 -0.06746417  1.02378711 -0.50466988]
 [ 1.60861933 -0.92299913 -0.89833872 -0.97676557 -0.50466988]]

In [8]:
from sklearn.svm import SVR
regressor=SVR(kernel='linear',C=100)
regressor=regressor.fit(x_train,y_train)

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [9]:
bias=regressor.intercept_
print("Bias",bias)
s=regressor.n_support_
print("Number of Support Vectors",s)
s1=regressor.support_
print(s1)

Bias [10411.59384646]
Number of Support Vectors [936]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890 891 892 893 894 895 896 897 898 899
 900 901 902 903 904 905 906 907 908 909 910 911 912 913 914 915 916 917
 918 919 920 921 922 923 924 925 926 927 928 929 930 931 932 933 934 935]

In [10]:
y_predict=regressor.predict(x_test)
print(y_predict)
print(y_test)

[10214.89324295  9228.45953281 25879.40397541 12377.17561436
  9608.37557208  4882.9579997   1149.72668746 11239.98982557
  7680.22673598  5518.86968102  6360.26448109 10335.94520411
  8191.78377428  5036.83850651 19285.79219956 10779.15419996
 11775.54129146  3448.63063335  6915.48141442 17501.95312887
 26285.97198125 12093.53040382 10180.20931381 24862.37349289
  2033.65564687  5139.73761352  3555.61488941  8272.28184236
  4546.61210665  8781.84517144  8168.28143356 28382.9098408
 12615.8943576  10776.91817924 18651.56114487  4337.09069396
  9229.40928316 20135.18231384 23937.92678564  1843.00724974
  5716.43774798  3729.54077554 22383.75446253 28415.95626406
 17471.40744924  2883.20629583 10771.19129163  7497.48641511
  4589.06923976 11722.06037652  2667.86924318  2640.25308685
 25179.81346134 27323.50723819 12020.68115024  3648.02914676
  3122.93486043  9202.31136444  9326.25620054 12171.93803834
  1124.21791495 29715.10712937 13176.834454   10137.23070689
 10485.52419863 10522.36136044 17229.09039991 21666.5729608
  2622.84332345  8271.97723491 12476.95700808 11472.19022579
 17420.27299342 13210.41406239 12114.08928496 12198.90632369
  8053.67228878  8524.18435838 22580.21275257 28790.85285458
 11179.24223296 24256.17738471  1993.59980496  8378.33006711
 24035.92759715 21837.93278838  4033.18423421  3017.84860049
 11986.30535064 20236.97487515  6273.37145318 10598.35599243
  3348.48154221  9062.96370486  5203.88733544  5345.32916792
 26684.76900808 24579.83159185  5509.160328   11111.67442294
  2266.8244843   6104.38524669  4727.49107975 21790.17876105
 24405.89025507  3394.11222695 10672.50796351  3977.40773067
 11505.2600717  28047.63485136 11667.18900299  5177.53724825
  9479.00198842 17002.4366693  27882.06622984  7889.29845719
  1621.30966067  9206.89606924 12217.95359298  9325.99046639
 24853.09241641  9877.61879725 13541.55080231  5410.09112372
  8396.23788167  4681.83747549 25217.62854673 24665.92792542
 28218.95803059  1845.85125689  8848.37498686  1380.58772184
  6899.01565433  9368.3987317  23257.47975708 21177.85443346
 23128.14282178 10271.27673645 26713.52362268  2537.74509991
  1809.70781491 10543.94278551 10000.58197043 10405.36364703
  5373.34119491 13451.54580815 12549.38322903  3178.70339197
   956.63488963 10625.24925925  6816.37031787 19614.68444363
 10003.20012799  1290.34142743  2129.41893806  7402.51356807
  2371.65773266  1274.41561076 10778.18899895 10130.9239913
  4506.08264748 12676.94332147 12157.64398052 10181.76231479
  4683.01954286  4140.59676681 17368.20373477  5850.54061733
  4625.21268174  1475.60267838  4123.44001499  4236.80327709
  8607.12259098  2608.81973558  4450.9455398   4403.68683555
  4129.06271438  6602.64734846 28902.79274906   799.71693197
 10993.63397915  7088.48198409 11222.26273214  3342.83218398
  5700.96736984 28425.05338321  1984.43039537  2335.27299042
 13379.0350823  10245.50546599 25400.44639698  4128.43826605
  6258.70049746 24697.03122409  2865.51534763  2366.07168163
  6666.86936083  6515.10644957  4747.95000533  4666.47502491
 11135.72368262 29123.15995054 11805.94835947 21461.70904648
  4613.78706497 25471.11446192  3401.56537279  9912.60359452
  6633.06612779  1207.15240821  9216.10162405 12824.50216517
  4962.57860788  2632.5187562   7295.08335986  2308.15962104
  6745.88348218  5380.75244848 13132.48680343  6709.70389497
  6818.73496072  7775.25117889  9083.08784204  2917.51929136
 11808.09562784 13152.81235631 12182.57019697 11617.46842841
  7115.45975582  2626.99004809   896.59898332  8863.29571796
 12121.13484883  2856.80835209  5154.94326875  7773.52219257
  9442.32435005 18560.58721037  6489.28408636 11063.44254569
  6428.05712945 18810.34569422  8237.18436696  7679.08030572
  8644.34017277 10500.42423516  2370.43952007  8304.71229242
  2123.54373023  7177.81143717 20811.81689804 29958.47388461
  4231.71477409  3764.30295941  1218.4972594    724.06930283
  8462.78515546  1403.9365034   4235.62120972  3832.49521776
  8933.44281222 26040.3188379  28553.4251175  13587.49507775
  7285.55199989 11373.55799042 21862.07776115  9303.06694241
 23630.16900822  1000.11679162 19571.68837835  5484.6167565
 12187.48070692  3790.54511906 22205.15562737  5911.32384705
 10108.61219308  9821.79120595  1872.14127308 12623.0525996
 11665.00457814  5231.39556422 11903.91302576  1241.42078338
  6707.05756419  3459.39292848  8834.56080147 24147.53270324
  3787.41618777   783.67046518  1721.92015461 29138.32895742
  9322.58782896  5110.47122872 11824.28717865 11400.38220299
 18651.72965155  7344.36020724  5761.90739491  9438.54431158
  1169.82366266  2238.01353803 19888.85464066 19540.72965559
 12780.82681947  2638.57246021  3525.4157095   9105.97249272
  9892.09307307 17104.87236579 22174.04061738  6578.08581546
 17647.94352093  1512.95636096  6947.35647039  5192.6668737
  8710.20615845  1487.66546605  7356.57877901 24343.60086967
  3191.41951177  4054.12949962  1320.39875951  9189.98385387
  4258.11271783 11558.83246707 29863.05134609 20732.72775816
  9455.54426805 24507.12742229 12367.35833379  4622.95647457
  9948.42497068  3565.56503955 28565.42107588  5298.2756187
 12328.31605258  1421.68155833 17696.20357141  3150.08487816
 27476.82688977  7033.06965589  2314.31277748 19322.00218495
  5597.94710958  5869.54275815 29775.12183798  1165.23895786
  8577.86195323  1882.38482249 11399.82782016  3487.8456637
  6176.5701674   5268.68917579 26242.56135846  8935.89468805
 21905.43951614 18590.42393677  6495.19594255  8900.93956859
  1103.34544311  3457.57419334  2308.04220712  9321.54983437
 27300.25467285 10973.48217187  1373.12286467 11522.34453307
  2163.76807881  8397.33544413  4150.91209855  2492.44022033
  3368.03634903 17390.88221917  6615.18325026  1016.40829799
 22512.64494255 11061.59290924 26250.54870069 11226.19632976
  5054.92057478  1932.7442848   1738.64489056 10465.76473992
  5679.86530908  1284.97547895 10574.31370829  7626.89938019
  7115.20573299  4114.80480178  2505.11222291 21090.09343202
  1710.6024654   9528.19109469  1435.78813672  8205.10314471
 11094.78340527  4084.60238567 19229.61810853 10800.56560397
 13579.49228487 12662.10709528]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [13]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.6288792857320369

In [12]:
import pickle
filename="Final_regressionAssignmentmodle.sav"
loaded_model=pickle.dump(regressor,open(filename,'wb'))