In [2]:
import pandas as pd

In [3]:
#datacollection
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#data preprocessing
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
#split input and output data
input_data=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
print(input_data)
output_data=dataset[['charges']]
print(output_data)

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]
          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
#split train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.30,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]
          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]
      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [29]:
#module creation
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=1000,criterion='poisson')
regressor=regressor.fit(x_train,y_train)

C:\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [30]:
y_predict=regressor.predict(x_test)
print(y_predict)
print(y_test)

[11297.47760844 10608.6875065  44831.20712647 13084.65738231
  9595.85761273 12428.30208551  1878.18374394 11401.71181225
  7363.52577339  5374.0109165   7519.14382317 18631.79518165
 10051.2062758   6912.88549625 24162.76333425 14159.32942708
 13332.91266403  3579.90793761  6516.85443384 33945.03073736
 23833.19109595 15092.34212615 10680.28301779 27459.87910581
  2995.52412568  5590.2261474   4630.58686043  8050.20375806
  3717.72673845  9238.84687978  7970.86906349 48449.20286165
 14177.42393371 12921.76679935 17308.6115226   3804.10036672
  8863.38547414 38003.99253802 39531.75285357  2965.52228256
  9705.01737749  3932.39420703 20677.63736167 47634.87679534
 37833.44505788  3721.61781232 14244.59706734  6598.95139224
  4975.82194136 12564.24102493  3696.89617123  4833.57666225
 26691.20613721 48470.62392211 11803.88362125  9558.92029085
  3775.83177822 11132.51952071  9557.30782793 16343.47543133
  1863.19158354 46846.44180695 15884.19703461 18468.90989231
 11897.32370064  9911.72756141 33873.66184913 40545.47235283
  3461.80171699 12293.89475853 18853.72956626 12357.86370985
 16975.97284066 14109.73342084 13286.28102545 15567.97198965
  8258.19824896 13774.17981009 19811.82984485 46713.09533764
 11546.8116343  49934.50285945  3976.95405367  9620.06319454
 40853.69416585 19245.86655097  3874.82279215  3346.79988224
 14307.24897711 39421.78699579  5757.3940003  14034.00259866
  2883.43280609 10086.02822219  9914.92421192  4205.2492783
 43262.38964349 52587.63449963  5458.94093224 10970.33426484
  3507.60141613  8029.33174044  7824.61664659 40249.60895534
 27416.50232678  3729.54536012 11287.7949287   6575.41284638
 11573.65584887 45325.24535845 12276.62921247  7117.39850341
 10472.17725285 34404.66334602 48053.91203825  7125.1367752
  2531.59957303 11375.0523904  21959.01953818  9410.87107899
 41821.66613011 12563.3725902  14582.31206559  8634.33287809
 10562.16522853  5339.78172489 26803.32734312 26188.39088215
 48510.74237681  1683.30961964 16172.30868147  3844.52708339
  6292.14645218  9173.41723883 41968.16766381 38224.99275699
 25286.82286175 16277.49534661 24238.66990714  6809.26801646
  2063.1465042  12173.68149336 10064.64850921 11184.96500892
  7046.4730099  14281.56682889 22521.34854033 13246.73091376
  1562.94593575 12492.93061526  6221.71840166 39125.77205359
  9910.36819756  9049.04209387  3546.63230348  8430.4320124
  3549.81530155  6458.91470322 14159.32942708 10679.93158077
  7173.00525114 13302.53263039 13858.91566683  9236.51474075
  4130.19120589  9810.09712267 17189.91001692  6701.84377272
  4647.98465545  2119.52825938  7774.85597775  6695.76298919
 12079.59471485  2350.68067314 11937.20691903  9713.74523175
  4742.73126777  7088.33376461 26975.55457284  1715.44542887
 17353.21783568  6850.96069228 11447.8448459   7960.84189979
  9158.05014361 28069.20102814  3477.38421453  3230.02950097
 14175.93467224 11055.90279984 41481.63433773  6937.34405243
  5488.13005862 24980.15102309  2948.76655722  2916.37556388
  9424.04298275  6330.04122129  9432.85436844  4431.34499479
 11988.62986232 46868.76998148 17260.20626045 18980.03186744
 10741.67525454 43458.95369479  4695.46540577  9881.90491425
  7328.90558371  1732.24800205  9160.28672062 13678.77222825
  6606.25320703  4343.89050077  6536.55991342 10197.3077535
  6939.78516551  6993.85436676 14101.52110272  6903.29633112
 13367.14195725  8065.94549719 12487.8884098   8285.0508458
 13802.24493867 14349.85526849 22627.69982322 12228.07431554
  7456.65365802  2797.58708439 10808.85967347  8272.52917366
 15052.84721046  4752.24942369  5457.48130192  7215.12844039
 14071.96428506 34472.16126223  5955.58509384 12761.7898807
  6067.0832231  37198.67115756  8308.79108982  7283.10624876
 12252.96777995 10472.61513631  3349.45957855  8412.61935239
  2871.16894299  6636.51088842 19659.32250543 46352.2587339
  5536.95770704  3679.81438566  5836.80864107  1630.63625242
  8264.85044134  3130.97253086  7149.76115885  9632.30704876
  8814.07133381 24990.13679487 45906.90321718 16518.04080941
  6529.07735019 11147.061298   44847.11712434 10338.63114435
 39659.78842088  1707.97208018 38829.31165961  5617.80099722
 12726.76106038  6237.7612926  40116.13162928  6528.58280841
 10006.4419502  11099.48169375  3877.91652269 17019.29856698
 12289.34956998 10923.80004916 13210.61976734 14290.9194756
  7660.82472001  5044.84216257 10769.93371447 22379.06388291
  3978.76196724  1676.71223829  2536.87644933 46935.33701367
 11614.51504369  4540.1664168  15480.14413146 13547.50902697
 34608.04535934  6867.54721738  5574.83812348  9145.97933296
  3239.02860374  4140.46471185 21048.02068361 16832.9565986
 13616.37945533  2844.30563042  3448.68094707 13429.45581885
 10181.18054816 15343.68505381 20185.09566744  9588.13727639
 16788.56118566  2558.66505846 12791.51679546  9935.00399286
 16904.62943262  2488.19701803  7209.63466189 46759.3560479
  3811.87423761  5794.63259004  1804.5658459  13660.73724192
  6394.90210157 11971.95580705 46795.89161035 17834.14038395
  9104.68351051 44196.45551742 16025.12750117 10783.30001756
 10542.88148732  5645.39668107 28476.8287998   4859.97978348
 14311.71213502  2312.31718219 16502.43684927  3412.87778838
 24453.95337287 12420.21796848  7625.60256477 40534.28203388
  6549.74819432  5257.4007749  29695.90922     3255.98115476
 10132.27319336  4001.84040529 11552.72757203  3948.9598216
  7767.65973017  6758.11719638 46826.88132416  9953.8456036
 45791.43726863 38752.09666053  5955.87089619 11723.714813
  1669.50572285  4729.78635812  3276.341351    9797.71517549
 46479.92551535 11529.86579302  1899.63458925 13582.76305481
  2139.2006584  12934.07113626  7902.17312622  2434.21158619
  3640.026885   36844.46366843  6747.14755417  1886.67754655
 40998.7900432  12523.63176378 43246.36489426 11771.68589525
  7627.95361064  3199.65796032  2116.3262401  16696.6795427
  5368.02342372  2111.75134268 11677.96842796  7159.01682891
  6098.70902555  6695.48255633  8074.76424181 43040.32734601
  4065.04864493 12755.7996286   6987.56056788 19302.85093624
 10974.12188749  6138.42098968 17077.29921999 12880.94935497
 20283.73023863 18880.22262191]
          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [31]:
#evaluation metrics
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.8576276734031387